blueprint:
  name: Z2M - IKEA 2 button remote
  description: |
    Control lights with an IKEA 2 button remote
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        entity:
          domain: sensor
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light
    force_brightness:
      name: Force turn on brightness
      description: >
        Force the brightness to the set level below, when the "on" button on
        the remote is pushed and lights turn on.
      default: false
      selector:
        boolean:
    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 50
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
          unit_of_measurement: "%"
    button_on:
      name: On button - short press
      description: Action to run on short on button press
      default: []
      selector:
        action:
    button_off:
      name: Off button - short press
      description: Action to run on short off button press
      default: []
      selector:
        action:
    brightness_move_up:
      name: On button - long press
      description: Action to run on long on button press
      default: []
      selector:
        action:
    brightness_move_down:
      name: Off button - long press
      description: Action to run on long off button press
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

variables:
  force_brightness: !input force_brightness

trigger:
  - platform: state
    entity_id: !input remote
    attribute: action

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'button_on' }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: !input light
                    data:
                      transition: 1
                      brightness_pct: !input brightness
            default:
              - service: light.turn_on
                target: !input light
                data:
                  transition: 1
                  
      - conditions:
          - "{{ command == 'button_off' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              transition: 1

      - conditions:
          - "{{ command == 'brightness_move_up' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: brightness_up_release
                  attribute: action
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 10
                    transition: 1
                  target: !input light
                - delay: '1'

      - conditions:
          - "{{ command == 'brightness_move_down' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: brightness_down_release
                  attribute: action
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: -10
                    transition: 1
                  target: !input light
                - delay: '1'

      - conditions:
          - "{{ command == 'on' }}"
        sequence: !input button_on

      - conditions:
          - "{{ command == 'off' }}"
        sequence: !input button_off

      - conditions:
          - "{{ command == 'brightness_move_up' }}"
        sequence: !input brightness_move_up

      - conditions:
          - "{{ command == 'brightness_move_down' }}"
        sequence: !input brightness_move_down
