esphome:
  name: nodemcuv3
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "0ev"
  password: "123789evhkn"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcuv3 Fallback Hotspot"
    password: "Cxk1GPrN3FNh"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    id: "button1"

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: rotary_encoder_1
    resolution: 1
    pin_a: 13
    pin_b: 12
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: rotary_encoder_1
              above: 1
          then:
          - logger.log: "up"
      - if:
          condition:
            sensor.in_range:
              id: rotary_encoder_1
              below: -1
          then:
          - logger.log: "down"
      - sensor.rotary_encoder.set_value:
          id: rotary_encoder_1
          value: 0